<?php

namespace SpaceSimulatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * logHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logHistoryRepository extends EntityRepository
{
    function getLastID() {
        $qb = $this->createQueryBuilder('l')
                ->select('coalesce(MAX(l.id + 1), 1) AS idMax');

        return $qb->getQuery()->getSingleResult();
    }
}
