<?php

namespace SpaceSimulatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * logHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logHistoryRepository extends EntityRepository
{
}
