space_simulator_homepage:
    path:     /simulator
    defaults: { _controller: SpaceSimulatorBundle:Simulation:index }

get_last_history:
    path:     /logHistory/getLastHistoryRecord
    defaults: { _controller: SpaceSimulatorBundle:LogHistory:getLastHistoryRecord }
    options:
        expose: true